Update CI and packaging scripts

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -3,7 +3,6 @@ name: Continuous Integration
 on:
   push:
   pull_request:
-    branches: [ develop ]
 
 jobs:
   linux:
@@ -19,12 +18,17 @@ jobs:
         with:
           dotnet-version: '6.0.x'
 
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+
       - name: Check Code
         run: |
           make check
           make check-packaging-scripts
 
-      - name: Check Mods
+      - name: Check Mod
         run: |
           sudo apt-get install lua5.1
           make check-scripts
@@ -38,12 +42,18 @@ jobs:
       - name: Clone Repository
         uses: actions/checkout@v2
 
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+
       - name: Check Code
         run: |
+          # check-packaging-scripts does not depend on .net/mono, so is not needed here
           mono --version
           make RUNTIME=mono check
 
-      - name: Check Mods
+      - name: Check Mod
         run: |
           # check-scripts does not depend on .net/mono, so is not needed here
           make RUNTIME=mono test
@@ -65,7 +75,7 @@ jobs:
         shell: powershell
         run: |
           # Work around runtime failures on the GH Actions runner
-          dotnet nuget locals all --clear
+          dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
           .\make.ps1 check
 
       - name: Check Mods
